version: "3"

services:
  app:
    build: .
    container_name: svelte-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  app-network:
    driver: bridge
