version: "3"

services:
  client:
    build: .
    container_name: svelte-todo-client
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver-todo
    restart: unless-stopped
    depends_on:
      - client
    ports:
      - "6080:80"
    networks:
      - app-network
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  app-network:
    driver: bridge
